name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install golint
      run: go get -u golang.org/x/lint/golint

    - name: Install pkger
      run:  go get -u github.com/markbates/pkger/cmd/pkger

    - name: Vet and test
      run: make -C kaybee check

    - name: Build
      run: make -C kaybee build-win build-linux build-macos
